-- AVISA WebFlotaElectricos — DATOS parte 4/4
-- AVISA WebFlotaElectricos — DATOS (continuación)
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.users (id, username, password, role, display_name, email, active, created_at) VALUES ('526d33f0-e052-481f-8d79-8d7772b0ce98', 'admin', '$2b$10$E1VUkla4FND6l3CZ64j40eAibp4eZ/Wc.yEFPN1D.uNfTZvqg/p76', 'superadmin', 'Administrador', 'admin@grupoavisa.com', true, '2026-03-11 11:05:51.981767');
INSERT INTO public.users (id, username, password, role, display_name, email, active, created_at) VALUES ('bb4dd411-f1df-40f0-9a91-6165f5cbaef8', 'contenidos', '$2b$10$Ngf/J8XH3K9nZ.EErAiObuONfXctOfq8CG/d4P.t.fHP.pU0XAOx6', 'editor', NULL, 'contenidos@grupoavisa.com', true, '2026-03-12 10:44:45.108034');


--
-- Data for Name: vehicles; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.vehicles (id, brand_id, model, slug, year, price, body_type, range_km, battery_kwh, power_hp, acceleration, top_speed, seats, drivetrain, charging_time_fast, charging_time_slow, trunk_liters, weight, image_url, gallery_urls, description, short_description, featured, available, meta_title, meta_description, video_url, vehicle_type) VALUES ('6884f5a6-3b28-4d87-8f75-a3b3ba8ed5af', 'aa102b7c-4238-4a5b-ab13-593b3c8f00a3', 'Model 3 Highland', 'tesla-model-3-highland', 2025, 40970, 'Berlina', 629, 60, 283, 6.1, 201, 5, 'RWD', '22 min (10-80%)', '6h 15min', 594, 1761, '/images/tesla-model-3.jpg', NULL, 'El Tesla Model 3 Highland presenta un diseño interior completamente renovado con materiales premium, iluminación ambiental y la mayor autonomía de su segmento. Tecnología de carga ultrarrápida y el sistema Autopilot más avanzado.', 'La berlina eléctrica más vendida del mundo, ahora con diseño renovado.', true, true, 'Tesla Model 3 Highland 2025 - AVISA Flota Eléctricos', 'Tesla Model 3 Highland 2025 con 629 km de autonomía. La berlina eléctrica más popular.', NULL, 'electrico');
INSERT INTO public.vehicles (id, brand_id, model, slug, year, price, body_type, range_km, battery_kwh, power_hp, acceleration, top_speed, seats, drivetrain, charging_time_fast, charging_time_slow, trunk_liters, weight, image_url, gallery_urls, description, short_description, featured, available, meta_title, meta_description, video_url, vehicle_type) VALUES ('66dba942-c7e9-4ea4-baf5-883f06771dac', 'a5c941c3-35d4-4de7-9191-8bde5cb82795', 'IONIQ 5 N', 'hyundai-ioniq-5-n', 2025, 68900, 'SUV', 448, 84, 650, 3.4, 260, 5, 'AWD', '18 min (10-80%)', '7h 20min', 527, 2231, '/images/hyundai-ioniq-5-n.jpg', NULL, 'El Hyundai IONIQ 5 N redefine los límites de los vehículos eléctricos de alto rendimiento. Con 650 CV, tracción total y un sistema de sonido que simula cambios de marcha, ofrece una experiencia de conducción emocionante y única en el segmento eléctrico.', 'El SUV eléctrico más deportivo del mercado con 650 CV y prestaciones de superdeportivo.', true, true, 'Hyundai IONIQ 5 N 2025 - AVISA Flota Eléctricos', 'Hyundai IONIQ 5 N 2025 con 650 CV. El SUV eléctrico deportivo definitivo.', NULL, 'electrico');
INSERT INTO public.vehicles (id, brand_id, model, slug, year, price, body_type, range_km, battery_kwh, power_hp, acceleration, top_speed, seats, drivetrain, charging_time_fast, charging_time_slow, trunk_liters, weight, image_url, gallery_urls, description, short_description, featured, available, meta_title, meta_description, video_url, vehicle_type) VALUES ('52510331-cdaf-4009-86f6-6692c7f91f54', '1ec729ac-e51a-4f27-ad8c-d5b2417bfd41', 'ID.4 Pro', 'volkswagen-id4-pro', 2025, 42495, 'SUV', 522, 77, 286, 6.7, 180, 5, 'RWD', '28 min (10-80%)', '7h 30min', 543, 2074, '/images/vw-id4.jpg', NULL, 'El Volkswagen ID.4 Pro combina la fiabilidad y calidad de construcción alemana con una plataforma 100% eléctrica. Su interior espacioso, infotainment intuitivo y autonomía superior a 500 km lo convierten en una opción ideal para flotas empresariales y particulares exigentes.', 'El SUV eléctrico de Volkswagen con calidad alemana y gran autonomía.', false, true, 'Volkswagen ID.4 Pro 2025 - AVISA Flota Eléctricos', 'Volkswagen ID.4 Pro 2025, SUV eléctrico con 522 km de autonomía y calidad alemana.', NULL, 'electrico');
INSERT INTO public.vehicles (id, brand_id, model, slug, year, price, body_type, range_km, battery_kwh, power_hp, acceleration, top_speed, seats, drivetrain, charging_time_fast, charging_time_slow, trunk_liters, weight, image_url, gallery_urls, description, short_description, featured, available, meta_title, meta_description, video_url, vehicle_type) VALUES ('ad23dbab-3f87-409b-bfd1-e8ae63aa4b09', 'fb4c0e95-10b3-4163-bf35-80c2df1eca06', 'iX1 xDrive30', 'bmw-ix1-xdrive30', 2025, 52850, 'SUV', 440, 64.7, 313, 5.6, 180, 5, 'AWD', '29 min (10-80%)', '6h 30min', 490, 2040, '/images/bmw-ix1.jpg', NULL, 'El BMW iX1 xDrive30 ofrece lo mejor de BMW en formato compacto y 100% eléctrico. Tracción integral, acabados premium y la última tecnología en conectividad y asistencia a la conducción.', 'Compacto premium eléctrico con la deportividad y lujo característicos de BMW.', false, true, 'BMW iX1 xDrive30 2025 - AVISA Flota Eléctricos', 'BMW iX1 xDrive30 2025. SUV compacto eléctrico premium con tracción integral.', NULL, 'electrico');
INSERT INTO public.vehicles (id, brand_id, model, slug, year, price, body_type, range_km, battery_kwh, power_hp, acceleration, top_speed, seats, drivetrain, charging_time_fast, charging_time_slow, trunk_liters, weight, image_url, gallery_urls, description, short_description, featured, available, meta_title, meta_description, video_url, vehicle_type) VALUES ('71516552-35fe-4737-b5ac-b69618c8074c', '9e5cb3be-0d30-4d26-9763-b42b654dd275', 'EQA 250+', 'mercedes-benz-eqa-250-plus', 2025, 53375, 'SUV', 528, 70.5, 190, 8.6, 160, 5, 'FWD', '32 min (10-80%)', '8h', 340, 2030, '/images/mercedes-eqa.jpg', NULL, 'El Mercedes-Benz EQA 250+ combina la elegancia y sofisticación de Mercedes con una plataforma eléctrica eficiente. Interior lujoso con MBUX, sistema de navegación con planificación de rutas eléctricas y una autonomía que supera los 500 km.', 'Lujo y eficiencia en formato SUV compacto eléctrico de Mercedes-Benz.', false, true, 'Mercedes-Benz EQA 250+ 2025 - AVISA Flota Eléctricos', 'Mercedes-Benz EQA 250+ 2025. SUV eléctrico de lujo con 528 km de autonomía.', NULL, 'electrico');
INSERT INTO public.vehicles (id, brand_id, model, slug, year, price, body_type, range_km, battery_kwh, power_hp, acceleration, top_speed, seats, drivetrain, charging_time_fast, charging_time_slow, trunk_liters, weight, image_url, gallery_urls, description, short_description, featured, available, meta_title, meta_description, video_url, vehicle_type) VALUES ('7e753674-b4e3-4a22-ad68-be3048066d87', '391d3419-54f6-4aec-9a24-59482238f27a', 'EV6 GT-Line', 'kia-ev6-gt-line', 2025, 52990, 'SUV', 528, 77.4, 325, 5.2, 185, 5, 'AWD', '18 min (10-80%)', '7h 10min', 490, 2090, '/images/kia-ev6.jpg', NULL, 'El Kia EV6 GT-Line impresiona con su plataforma E-GMP de 800V que permite cargas ultra-rápidas, diseño futurista y un rendimiento excepcional. Ganador de múltiples premios internacionales, es uno de los eléctricos más completos del mercado.', 'Crossover eléctrico con carga ultra-rápida a 800V y diseño vanguardista.', true, true, 'Kia EV6 GT-Line 2025 - AVISA Flota Eléctricos', 'Kia EV6 GT-Line 2025 con carga ultra-rápida 800V y 528 km de autonomía.', NULL, 'electrico');
INSERT INTO public.vehicles (id, brand_id, model, slug, year, price, body_type, range_km, battery_kwh, power_hp, acceleration, top_speed, seats, drivetrain, charging_time_fast, charging_time_slow, trunk_liters, weight, image_url, gallery_urls, description, short_description, featured, available, meta_title, meta_description, video_url, vehicle_type) VALUES ('ad2a2bd6-4325-47ad-bdbd-f05169b32535', '3e04d435-4df7-4861-8bd1-784b93c661f2', 'EX30 Single Motor', 'volvo-ex30-single-motor', 2025, 36695, 'Compacto', 476, 69, 272, 5.3, 180, 5, 'RWD', '25 min (10-80%)', '6h', 318, 1790, '/images/volvo-ex30.jpg', NULL, 'El Volvo EX30 es el eléctrico más pequeño de Volvo pero no escatima en seguridad ni tecnología. Fabricado con materiales reciclados, ofrece un interior minimalista escandinavo y todos los sistemas de seguridad activa de Volvo.', 'El SUV compacto eléctrico más seguro y sostenible del mercado.', false, true, 'Volvo EX30 Single Motor 2025 - AVISA Flota Eléctricos', 'Volvo EX30 2025. El SUV compacto eléctrico más seguro con 476 km de autonomía.', NULL, 'electrico');
INSERT INTO public.vehicles (id, brand_id, model, slug, year, price, body_type, range_km, battery_kwh, power_hp, acceleration, top_speed, seats, drivetrain, charging_time_fast, charging_time_slow, trunk_liters, weight, image_url, gallery_urls, description, short_description, featured, available, meta_title, meta_description, video_url, vehicle_type) VALUES ('fe9d11fa-e250-43eb-a8fc-2b68837f80ae', 'a86a022e-1293-4cf4-9ecb-41fb1e0c46fa', 'e-3008', 'peugeot-e-3008', 2025, 44900, 'SUV', 527, 73, 213, 8.7, 170, 5, 'FWD', '30 min (10-80%)', '7h 45min', 520, 2037, '/images/peugeot-e3008.jpg', NULL, 'El Peugeot e-3008 marca una nueva era para la marca con un diseño revolucionario y el innovador i-Cockpit panorámico de 21 pulgadas. Autonomía superior a 500 km y un interior que redefine el concepto de confort en el segmento eléctrico.', 'El nuevo SUV eléctrico de Peugeot con el innovador i-Cockpit panorámico.', false, true, 'Peugeot e-3008 2025 - AVISA Flota Eléctricos', 'Peugeot e-3008 2025. SUV eléctrico innovador con 527 km de autonomía.', NULL, 'electrico');
INSERT INTO public.vehicles (id, brand_id, model, slug, year, price, body_type, range_km, battery_kwh, power_hp, acceleration, top_speed, seats, drivetrain, charging_time_fast, charging_time_slow, trunk_liters, weight, image_url, gallery_urls, description, short_description, featured, available, meta_title, meta_description, video_url, vehicle_type) VALUES ('dd0d10c0-c4c6-4528-8b9e-90c515d40450', '374876c4-057e-4acf-9f71-e430c3d793b6', 'Scenic E-Tech', 'renault-scenic-e-tech', 2025, 39990, 'SUV', 625, 87, 220, 7.9, 170, 5, 'FWD', '30 min (15-80%)', '9h', 545, 2058, '/images/renault-scenic.jpg', NULL, 'El Renault Scenic E-Tech reinventa el monovolumen como un SUV eléctrico familiar con una autonomía líder de 625 km. Interior amplísimo, sistema multimedia openR link con Google integrado y un compromiso firme con la sostenibilidad usando materiales reciclados.', 'El familiar eléctrico con la mayor autonomía de su categoría: 625 km.', true, true, 'Renault Scenic E-Tech 2025 - AVISA Flota Eléctricos', 'Renault Scenic E-Tech 2025 con 625 km de autonomía. El familiar eléctrico definitivo.', NULL, 'electrico');
INSERT INTO public.vehicles (id, brand_id, model, slug, year, price, body_type, range_km, battery_kwh, power_hp, acceleration, top_speed, seats, drivetrain, charging_time_fast, charging_time_slow, trunk_liters, weight, image_url, gallery_urls, description, short_description, featured, available, meta_title, meta_description, video_url, vehicle_type) VALUES ('e3ecc6c6-1d6e-4c6a-b47d-2cfc75cd0ca5', '63bfae21-0b75-4842-a548-26cc8fae8aa1', 'Dolphin', 'byd-dolphin', 2025, 29990, 'Compacto', 427, 60.4, 204, 7, 160, 5, 'FWD', '29 min (10-80%)', '7h 30min', 345, 1625, '/images/byd-dolphin.jpg', NULL, 'El BYD Dolphin democratiza la movilidad eléctrica con un precio competitivo sin renunciar a prestaciones. Batería Blade segura, diseño joven y fresco, y un equipamiento de serie que avergüenza a rivales más caros.', 'El compacto eléctrico más accesible con tecnología de primer nivel.', false, true, 'BYD Dolphin 2025 - AVISA Flota Eléctricos', 'BYD Dolphin 2025. Compacto eléctrico accesible con 427 km de autonomía.', NULL, 'electrico');
INSERT INTO public.vehicles (id, brand_id, model, slug, year, price, body_type, range_km, battery_kwh, power_hp, acceleration, top_speed, seats, drivetrain, charging_time_fast, charging_time_slow, trunk_liters, weight, image_url, gallery_urls, description, short_description, featured, available, meta_title, meta_description, video_url, vehicle_type) VALUES ('8eda3adb-1a6c-4ba5-8d92-753cb01769c7', 'aa102b7c-4238-4a5b-ab13-593b3c8f00a3', 'Model Y Long Range', 'tesla-model-y-long-range', 2025, 48990, 'SUV', 533, 75, 350, 5, 217, 5, 'AWD', '27 min (10-80%)', '7h 30min', 854, 1979, '/images/tesla-model-y.jpg', NULL, 'El Tesla Model Y Long Range combina espacio, rendimiento y tecnología de vanguardia. Con tracción total y una autonomía superior a 500 km, es la opción ideal para familias y profesionales que buscan un SUV eléctrico sin compromiso.', 'SUV eléctrico versátil con la mejor autonomía de su clase y tecnología Autopilot.', true, true, 'Tesla Model Y Long Range 2025 - AVISA Flota Eléctricos', 'Descubre el Tesla Model Y Long Range 2025. SUV eléctrico con 533 km de autonomía y tracción total.', NULL, 'electrico');
INSERT INTO public.vehicles (id, brand_id, model, slug, year, price, body_type, range_km, battery_kwh, power_hp, acceleration, top_speed, seats, drivetrain, charging_time_fast, charging_time_slow, trunk_liters, weight, image_url, gallery_urls, description, short_description, featured, available, meta_title, meta_description, video_url, vehicle_type) VALUES ('a78742d0-d220-442b-bb68-1ca244502bc6', '63bfae21-0b75-4842-a548-26cc8fae8aa1', 'Seal U', 'byd-seal-u', 2025, 38990, 'SUV', 500, 87.4, 218, 7.5, 185, 5, 'FWD', '34 min (10-80%)', '8h 30min', 552, 2105, '/images/byd-seal-u.jpg', NULL, 'El BYD Seal U es un SUV eléctrico espacioso y tecnológico que destaca por su batería Blade de litio-ferrofosfato, ofreciendo máxima seguridad y durabilidad. Equipamiento completo de serie y un diseño moderno que se adapta perfectamente a las necesidades de las flotas empresariales.', 'SUV familiar con la tecnología Blade Battery y una excelente relación calidad-precio.', true, true, 'BYD Seal U 2025 - AVISA Flota Eléctricos', 'BYD Seal U 2025, SUV eléctrico con 500 km de autonomía y tecnología Blade Battery.', NULL, 'electrico');


--
-- PostgreSQL database dump complete
--

\unrestrict sh7RDF5FuvgIuIGM9m585MvOfSzjL6FcXjB73Lgh9JR76naVkhMHBR4eMRl8KSc

