import { storage } from "./storage";
import type { InsertPromotion } from "@shared/schema";

const promotionsList: InsertPromotion[] = [
  {
    title: "Volkswagen ID.3 Pro",
    subtitle: "100% Eléctrico",
    vehicleType: "electrico",
    brandName: "Volkswagen",
    modelName: "ID.3 Pro",
    imageUrl: "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=480&h=320&fit=crop&auto=format&q=80",
    price: 42900,
    monthlyPayment: "399€/mes",
    features: ["Autonomía: 426 km", "Potencia: 204 CV", "Batería: 58 kWh", "Carga rápida: 30 min (80%)", "Aceleración: 7.3 s (0-100)", "Consumo: 14.5 kWh/100km"],
    badge: "Más vendido",
    link: "/vehiculos/electricos/volkswagen-id3-pro",
    active: true,
    sortOrder: 1,
  },
  {
    title: "Volkswagen ID.4 Pro",
    subtitle: "100% Eléctrico",
    vehicleType: "electrico",
    brandName: "Volkswagen",
    modelName: "ID.4 Pro",
    imageUrl: "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=480&h=320&fit=crop&auto=format&q=80",
    price: 52400,
    monthlyPayment: "485€/mes",
    features: ["Autonomía: 521 km", "Potencia: 204 CV", "Batería: 77 kWh", "Carga rápida: 38 min (80%)", "Aceleración: 8.5 s (0-100)", "Consumo: 16.3 kWh/100km"],
    badge: "SUV familiar",
    link: "/vehiculos/electricos/volkswagen-id4-pro",
    active: true,
    sortOrder: 2,
  },
  {
    title: "Volkswagen ID.5 GTX",
    subtitle: "100% Eléctrico",
    vehicleType: "electrico",
    brandName: "Volkswagen",
    modelName: "ID.5 GTX",
    imageUrl: "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=480&h=320&fit=crop&auto=format&q=80",
    price: 64900,
    monthlyPayment: "599€/mes",
    features: ["Autonomía: 490 km", "Potencia: 299 CV", "Batería: 77 kWh", "Carga rápida: 36 min (80%)", "Aceleración: 6.3 s (0-100)", "Consumo: 17.2 kWh/100km"],
    badge: "Deportivo",
    link: "/vehiculos/electricos/volkswagen-id5-gtx",
    active: true,
    sortOrder: 3,
  },
  {
    title: "Audi Q4 e-tron 45",
    subtitle: "100% Eléctrico",
    vehicleType: "electrico",
    brandName: "Audi",
    modelName: "Q4 e-tron 45",
    imageUrl: "https://images.unsplash.com/photo-1617788822097-7c40bc68e3be?w=480&h=320&fit=crop&auto=format&q=80",
    price: 59400,
    monthlyPayment: "549€/mes",
    features: ["Autonomía: 520 km", "Potencia: 286 CV", "Batería: 82 kWh", "Carga rápida: 38 min (80%)", "Aceleración: 6.2 s (0-100)", "Consumo: 17.0 kWh/100km"],
    badge: "SUV versátil",
    link: "/vehiculos/electricos/audi-q4-etron-45",
    active: true,
    sortOrder: 4,
  },
  {
    title: "Audi e-tron GT quattro",
    subtitle: "100% Eléctrico",
    vehicleType: "electrico",
    brandName: "Audi",
    modelName: "e-tron GT quattro",
    imageUrl: "https://images.unsplash.com/photo-1621007947382-bb5c3a707c56?w=480&h=320&fit=crop&auto=format&q=80",
    price: 107900,
    monthlyPayment: "999€/mes",
    features: ["Autonomía: 488 km", "Potencia: 476 CV", "Batería: 93.4 kWh", "Carga rápida: 23 min (80%)", "Aceleración: 4.1 s (0-100)", "Consumo: 19.6 kWh/100km"],
    badge: "Gran Turismo",
    link: "/vehiculos/electricos/audi-etron-gt-quattro",
    active: true,
    sortOrder: 5,
  },
  {
    title: "Audi Q8 e-tron 55",
    subtitle: "100% Eléctrico",
    vehicleType: "electrico",
    brandName: "Audi",
    modelName: "Q8 e-tron 55",
    imageUrl: "https://images.unsplash.com/photo-1617788822097-7c40bc68e3be?w=480&h=320&fit=crop&auto=format&q=80",
    price: 97100,
    monthlyPayment: "899€/mes",
    features: ["Autonomía: 582 km", "Potencia: 408 CV", "Batería: 114 kWh", "Carga rápida: 31 min (80%)", "Aceleración: 5.6 s (0-100)", "Consumo: 20.6 kWh/100km"],
    badge: "Flagship SUV",
    link: "/vehiculos/electricos/audi-q8-etron-55",
    active: true,
    sortOrder: 6,
  },
  {
    title: "CUPRA Born e-Boost",
    subtitle: "100% Eléctrico",
    vehicleType: "electrico",
    brandName: "CUPRA",
    modelName: "Born e-Boost",
    imageUrl: "https://images.unsplash.com/photo-1566024287286-457156ae0bea?w=480&h=320&fit=crop&auto=format&q=80",
    price: 46400,
    monthlyPayment: "429€/mes",
    features: ["Autonomía: 548 km", "Potencia: 231 CV", "Batería: 77 kWh", "Carga rápida: 35 min (80%)", "Aceleración: 6.6 s (0-100)", "Consumo: 15.4 kWh/100km"],
    badge: "Deportivo compacto",
    link: "/vehiculos/electricos/cupra-born-eboost",
    active: true,
    sortOrder: 7,
  },
  {
    title: "CUPRA Tavascan VZ",
    subtitle: "100% Eléctrico",
    vehicleType: "electrico",
    brandName: "CUPRA",
    modelName: "Tavascan VZ",
    imageUrl: "https://images.unsplash.com/photo-1566024287286-457156ae0bea?w=480&h=320&fit=crop&auto=format&q=80",
    price: 70100,
    monthlyPayment: "649€/mes",
    features: ["Autonomía: 520 km", "Potencia: 340 CV", "Batería: 77 kWh", "Carga rápida: 35 min (80%)", "Aceleración: 5.6 s (0-100)", "Consumo: 16.8 kWh/100km"],
    badge: "SUV Coupé",
    link: "/vehiculos/electricos/cupra-tavascan-vz",
    active: true,
    sortOrder: 8,
  },
  {
    title: "CUPRA Born VZ",
    subtitle: "100% Eléctrico",
    vehicleType: "electrico",
    brandName: "CUPRA",
    modelName: "Born VZ",
    imageUrl: "https://images.unsplash.com/photo-1566024287286-457156ae0bea?w=480&h=320&fit=crop&auto=format&q=80",
    price: 51800,
    monthlyPayment: "479€/mes",
    features: ["Autonomía: 511 km", "Potencia: 326 CV", "Batería: 77 kWh", "Carga rápida: 35 min (80%)", "Aceleración: 5.6 s (0-100)", "Consumo: 16.2 kWh/100km"],
    badge: "Máxima potencia",
    link: "/vehiculos/electricos/cupra-born-vz",
    active: true,
    sortOrder: 9,
  },
  {
    title: "Škoda Enyaq iV 80",
    subtitle: "100% Eléctrico",
    vehicleType: "electrico",
    brandName: "Škoda",
    modelName: "Enyaq iV 80",
    imageUrl: "https://images.unsplash.com/photo-1619767886558-f0d5f41d8bce?w=480&h=320&fit=crop&auto=format&q=80",
    price: 53900,
    monthlyPayment: "499€/mes",
    features: ["Autonomía: 534 km", "Potencia: 204 CV", "Batería: 82 kWh", "Carga rápida: 36 min (80%)", "Aceleración: 8.6 s (0-100)", "Consumo: 16.7 kWh/100km"],
    badge: "SUV espacioso",
    link: "/vehiculos/electricos/skoda-enyaq-iv-80",
    active: true,
    sortOrder: 10,
  },
  {
    title: "Škoda Enyaq Coupé RS",
    subtitle: "100% Eléctrico",
    vehicleType: "electrico",
    brandName: "Škoda",
    modelName: "Enyaq Coupé RS",
    imageUrl: "https://images.unsplash.com/photo-1619767886558-f0d5f41d8bce?w=480&h=320&fit=crop&auto=format&q=80",
    price: 70200,
    monthlyPayment: "649€/mes",
    features: ["Autonomía: 513 km", "Potencia: 340 CV", "Batería: 82 kWh", "Carga rápida: 36 min (80%)", "Aceleración: 6.5 s (0-100)", "Consumo: 17.4 kWh/100km"],
    badge: "Deportivo",
    link: "/vehiculos/electricos/skoda-enyaq-coupe-rs",
    active: true,
    sortOrder: 11,
  },
  {
    title: "Škoda Enyaq iV 60",
    subtitle: "100% Eléctrico",
    vehicleType: "electrico",
    brandName: "Škoda",
    modelName: "Enyaq iV 60",
    imageUrl: "https://images.unsplash.com/photo-1619767886558-f0d5f41d8bce?w=480&h=320&fit=crop&auto=format&q=80",
    price: 46400,
    monthlyPayment: "429€/mes",
    features: ["Autonomía: 417 km", "Potencia: 180 CV", "Batería: 62 kWh", "Carga rápida: 36 min (80%)", "Aceleración: 9.0 s (0-100)", "Consumo: 15.9 kWh/100km"],
    badge: "Mejor precio",
    link: "/vehiculos/electricos/skoda-enyaq-iv-60",
    active: true,
    sortOrder: 12,
  },

  {
    title: "Volkswagen Golf GTE",
    subtitle: "Híbrido Enchufable",
    vehicleType: "hibrido",
    brandName: "Volkswagen",
    modelName: "Golf GTE",
    imageUrl: "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=480&h=320&fit=crop&auto=format&q=80",
    price: 40900,
    monthlyPayment: "379€/mes",
    features: ["Autonomía eléctrica: 62 km", "Potencia: 245 CV", "Batería: 13 kWh", "Tiempo carga: 3h 40min", "Aceleración: 6.7 s (0-100)", "Consumo: 1.3 l/100km"],
    badge: "Compacto deportivo",
    link: "/vehiculos/hibridos/volkswagen-golf-gte",
    active: true,
    sortOrder: 13,
  },
  {
    title: "Volkswagen Tiguan eHybrid",
    subtitle: "Híbrido Enchufable",
    vehicleType: "hibrido",
    brandName: "Volkswagen",
    modelName: "Tiguan eHybrid",
    imageUrl: "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=480&h=320&fit=crop&auto=format&q=80",
    price: 51800,
    monthlyPayment: "479€/mes",
    features: ["Autonomía eléctrica: 50 km", "Potencia: 245 CV", "Batería: 13 kWh", "Tiempo carga: 3h 50min", "Aceleración: 7.5 s (0-100)", "Consumo: 1.6 l/100km"],
    badge: "SUV familiar",
    link: "/vehiculos/hibridos/volkswagen-tiguan-ehybrid",
    active: true,
    sortOrder: 14,
  },
  {
    title: "Volkswagen Touareg eHybrid",
    subtitle: "Híbrido Enchufable",
    vehicleType: "hibrido",
    brandName: "Volkswagen",
    modelName: "Touareg eHybrid",
    imageUrl: "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=480&h=320&fit=crop&auto=format&q=80",
    price: 80900,
    monthlyPayment: "749€/mes",
    features: ["Autonomía eléctrica: 47 km", "Potencia: 462 CV", "Batería: 14.3 kWh", "Tiempo carga: 4h 30min", "Aceleración: 5.7 s (0-100)", "Consumo: 2.7 l/100km"],
    badge: "Premium SUV",
    link: "/vehiculos/hibridos/volkswagen-touareg-ehybrid",
    active: true,
    sortOrder: 15,
  },
  {
    title: "Audi A3 Sportback TFSI e",
    subtitle: "Híbrido Enchufable",
    vehicleType: "hibrido",
    brandName: "Audi",
    modelName: "A3 Sportback TFSI e",
    imageUrl: "https://images.unsplash.com/photo-1617788822097-7c40bc68e3be?w=480&h=320&fit=crop&auto=format&q=80",
    price: 46400,
    monthlyPayment: "429€/mes",
    features: ["Autonomía eléctrica: 67 km", "Potencia: 204 CV", "Batería: 13 kWh", "Tiempo carga: 3h 45min", "Aceleración: 7.6 s (0-100)", "Consumo: 1.1 l/100km"],
    badge: "Compacto premium",
    link: "/vehiculos/hibridos/audi-a3-tfsi-e",
    active: true,
    sortOrder: 16,
  },
  {
    title: "Audi Q3 TFSI e",
    subtitle: "Híbrido Enchufable",
    vehicleType: "hibrido",
    brandName: "Audi",
    modelName: "Q3 TFSI e",
    imageUrl: "https://images.unsplash.com/photo-1617788822097-7c40bc68e3be?w=480&h=320&fit=crop&auto=format&q=80",
    price: 53900,
    monthlyPayment: "499€/mes",
    features: ["Autonomía eléctrica: 53 km", "Potencia: 245 CV", "Batería: 13 kWh", "Tiempo carga: 3h 45min", "Aceleración: 7.3 s (0-100)", "Consumo: 1.4 l/100km"],
    badge: "SUV compacto",
    link: "/vehiculos/hibridos/audi-q3-tfsi-e",
    active: true,
    sortOrder: 17,
  },
  {
    title: "Audi Q5 TFSI e quattro",
    subtitle: "Híbrido Enchufable",
    vehicleType: "hibrido",
    brandName: "Audi",
    modelName: "Q5 TFSI e quattro",
    imageUrl: "https://images.unsplash.com/photo-1617788822097-7c40bc68e3be?w=480&h=320&fit=crop&auto=format&q=80",
    price: 69400,
    monthlyPayment: "639€/mes",
    features: ["Autonomía eléctrica: 62 km", "Potencia: 299 CV", "Batería: 14.4 kWh", "Tiempo carga: 2h 30min", "Aceleración: 6.1 s (0-100)", "Consumo: 1.7 l/100km"],
    badge: "Premium versátil",
    link: "/vehiculos/hibridos/audi-q5-tfsi-e",
    active: true,
    sortOrder: 18,
  },
  {
    title: "SEAT León e-HYBRID",
    subtitle: "Híbrido Enchufable",
    vehicleType: "hibrido",
    brandName: "SEAT",
    modelName: "León e-HYBRID",
    imageUrl: "https://images.unsplash.com/photo-1502877338535-e2e1c07b8e44?w=480&h=320&fit=crop&auto=format&q=80",
    price: 37900,
    monthlyPayment: "349€/mes",
    features: ["Autonomía eléctrica: 60 km", "Potencia: 204 CV", "Batería: 12.8 kWh", "Tiempo carga: 3h 30min", "Aceleración: 7.5 s (0-100)", "Consumo: 1.2 l/100km"],
    badge: "Mejor relación calidad-precio",
    link: "/vehiculos/hibridos/seat-leon-ehybrid",
    active: true,
    sortOrder: 19,
  },
  {
    title: "SEAT León Sportstourer e-HYBRID",
    subtitle: "Híbrido Enchufable",
    vehicleType: "hibrido",
    brandName: "SEAT",
    modelName: "León Sportstourer e-HYBRID",
    imageUrl: "https://images.unsplash.com/photo-1502877338535-e2e1c07b8e44?w=480&h=320&fit=crop&auto=format&q=80",
    price: 39900,
    monthlyPayment: "369€/mes",
    features: ["Autonomía eléctrica: 60 km", "Potencia: 204 CV", "Batería: 12.8 kWh", "Tiempo carga: 3h 30min", "Aceleración: 7.7 s (0-100)", "Consumo: 1.3 l/100km"],
    badge: "Familiar versátil",
    link: "/vehiculos/hibridos/seat-leon-sportstourer-ehybrid",
    active: true,
    sortOrder: 20,
  },
  {
    title: "SEAT Tarraco e-HYBRID",
    subtitle: "Híbrido Enchufable",
    vehicleType: "hibrido",
    brandName: "SEAT",
    modelName: "Tarraco e-HYBRID",
    imageUrl: "https://images.unsplash.com/photo-1502877338535-e2e1c07b8e44?w=480&h=320&fit=crop&auto=format&q=80",
    price: 48900,
    monthlyPayment: "449€/mes",
    features: ["Autonomía eléctrica: 49 km", "Potencia: 245 CV", "Batería: 13 kWh", "Tiempo carga: 3h 45min", "Aceleración: 7.4 s (0-100)", "Consumo: 1.7 l/100km"],
    badge: "SUV 7 plazas",
    link: "/vehiculos/hibridos/seat-tarraco-ehybrid",
    active: true,
    sortOrder: 21,
  },
  {
    title: "CUPRA León e-HYBRID",
    subtitle: "Híbrido Enchufable",
    vehicleType: "hibrido",
    brandName: "CUPRA",
    modelName: "León e-HYBRID",
    imageUrl: "https://images.unsplash.com/photo-1502877338535-e2e1c07b8e44?w=480&h=320&fit=crop&auto=format&q=80",
    price: 43900,
    monthlyPayment: "399€/mes",
    features: ["Autonomía eléctrica: 60 km", "Potencia: 245 CV", "Batería: 12.8 kWh", "Tiempo carga: 3h 30min", "Aceleración: 6.7 s (0-100)", "Consumo: 1.3 l/100km"],
    badge: "Deportivo",
    link: "/vehiculos/hibridos/cupra-leon-ehybrid",
    active: true,
    sortOrder: 22,
  },
  {
    title: "CUPRA Formentor e-HYBRID",
    subtitle: "Híbrido Enchufable",
    vehicleType: "hibrido",
    brandName: "CUPRA",
    modelName: "Formentor e-HYBRID",
    imageUrl: "https://images.unsplash.com/photo-1566024287286-457156ae0bea?w=480&h=320&fit=crop&auto=format&q=80",
    price: 46900,
    monthlyPayment: "429€/mes",
    features: ["Autonomía eléctrica: 55 km", "Potencia: 204 CV", "Batería: 12.8 kWh", "Tiempo carga: 3h 30min", "Aceleración: 7.0 s (0-100)", "Consumo: 1.4 l/100km"],
    badge: "Crossover deportivo",
    link: "/vehiculos/hibridos/cupra-formentor-ehybrid",
    active: true,
    sortOrder: 23,
  },
  {
    title: "CUPRA Formentor VZ e-HYBRID",
    subtitle: "Híbrido Enchufable",
    vehicleType: "hibrido",
    brandName: "CUPRA",
    modelName: "Formentor VZ e-HYBRID",
    imageUrl: "https://images.unsplash.com/photo-1566024287286-457156ae0bea?w=480&h=320&fit=crop&auto=format&q=80",
    price: 53900,
    monthlyPayment: "499€/mes",
    features: ["Autonomía eléctrica: 55 km", "Potencia: 245 CV", "Batería: 12.8 kWh", "Tiempo carga: 3h 30min", "Aceleración: 6.7 s (0-100)", "Consumo: 1.5 l/100km"],
    badge: "Máximo rendimiento",
    link: "/vehiculos/hibridos/cupra-formentor-vz-ehybrid",
    active: true,
    sortOrder: 24,
  },
  {
    title: "Škoda Octavia iV",
    subtitle: "Híbrido Enchufable",
    vehicleType: "hibrido",
    brandName: "Škoda",
    modelName: "Octavia iV",
    imageUrl: "https://images.unsplash.com/photo-1619767886558-f0d5f41d8bce?w=480&h=320&fit=crop&auto=format&q=80",
    price: 39900,
    monthlyPayment: "369€/mes",
    features: ["Autonomía eléctrica: 59 km", "Potencia: 204 CV", "Batería: 13 kWh", "Tiempo carga: 3h 30min", "Aceleración: 7.8 s (0-100)", "Consumo: 1.2 l/100km"],
    badge: "Berlina versátil",
    link: "/vehiculos/hibridos/skoda-octavia-iv",
    active: true,
    sortOrder: 25,
  },
  {
    title: "Škoda Octavia Combi iV",
    subtitle: "Híbrido Enchufable",
    vehicleType: "hibrido",
    brandName: "Škoda",
    modelName: "Octavia Combi iV",
    imageUrl: "https://images.unsplash.com/photo-1619767886558-f0d5f41d8bce?w=480&h=320&fit=crop&auto=format&q=80",
    price: 41900,
    monthlyPayment: "389€/mes",
    features: ["Autonomía eléctrica: 59 km", "Potencia: 204 CV", "Batería: 13 kWh", "Tiempo carga: 3h 30min", "Aceleración: 7.9 s (0-100)", "Consumo: 1.2 l/100km"],
    badge: "Familiar espacioso",
    link: "/vehiculos/hibridos/skoda-octavia-combi-iv",
    active: true,
    sortOrder: 26,
  },
  {
    title: "Škoda Superb iV",
    subtitle: "Híbrido Enchufable",
    vehicleType: "hibrido",
    brandName: "Škoda",
    modelName: "Superb iV",
    imageUrl: "https://images.unsplash.com/photo-1619767886558-f0d5f41d8bce?w=480&h=320&fit=crop&auto=format&q=80",
    price: 49900,
    monthlyPayment: "459€/mes",
    features: ["Autonomía eléctrica: 62 km", "Potencia: 204 CV", "Batería: 13 kWh", "Tiempo carga: 3h 30min", "Aceleración: 7.7 s (0-100)", "Consumo: 1.3 l/100km"],
    badge: "Ejecutivo premium",
    link: "/vehiculos/hibridos/skoda-superb-iv",
    active: true,
    sortOrder: 27,
  },
];

export async function seedPromotions() {
  const existing = await storage.getPromotions();
  if (existing.length > 0) return;

  for (const promo of promotionsList) {
    await storage.createPromotion(promo);
  }
  console.log(`Seeded ${promotionsList.length} promotions`);
}
